---

kind: pipeline
name: buildtest

steps:
  - name: Lint Dockerfile
    image: hadolint/hadolint:latest-alpine
    pull: if-not-exists
    commands:
      - hadolint --version
      - hadolint Dockerfile*

  - name: Build Test
    image: docker
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands: 
      - "docker build -t dnscrypt:test ."

  - name: Test Run
    image: dnscrypt:test
    pull: if-not-exists
    detach: true

  - name: Pause
    image: busybox:latest
    commands:
      - sleep 5

  - name: Testing
    image: dnscrypt:test
    pull: if-not-exists
    commands:
      - drill -p 53 -D one.one.one.one || exit 1

volumes: 
  - name: dockersock
    host: 
      path: /var/run/docker.sock

trigger:
  event:
    - promote
    - custom

---

kind: pipeline
type: docker
name: deploy

platform:
  os: linux
  arch: amd64

steps:
  - name: Lint Dockerfile
    image: hadolint/hadolint:latest-alpine
    pull: if-not-exists
    commands:
      - hadolint --version
      - hadolint Dockerfile*

  - name: deploy
    image: thegeeklab/drone-docker-buildx
    settings:
      repo: modem7/dnscrypt-proxy
      # dry_run: true  # disable when not testing
      purge: true
      compress: true
      use_cache: true
      cache_from: "modem7/dnscrypt-proxy:latest"
      platforms:  # if it doesn't work run docker run --privileged --rm tonistiigi/binfmt --install all
        - linux/386
        - linux/amd64
        - linux/arm/v6
        - linux/arm/v7
        - linux/arm64/v8
        - linux/ppc64le
        - linux/s390x
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - latest
        - 2.1.0

  - name: slack
    image: themaz/drone-slack
    settings:
      webhook:
        from_secret: slack_hook
    when:
      status: [ success, failure ]

# Doesn't work currently - https://github.com/christian-korneck/docker-pushrm/blob/master/README.md#limitations
# https://github.com/docker/roadmap/issues/115

# - name: pushrm-dockerhub
  # image: chko/docker-pushrm:1
  # environment:
    # DOCKER_PASS:
      # from_secret: docker_password
    # DOCKER_USER:
      # from_secret: docker_username
    # PUSHRM_FILE: README.md
    # PUSHRM_SHORT: A DNS server container using several UK/European DoH resolution services via DNSCrypt Proxy
    # PUSHRM_TARGET: modem7/dnscrypt-proxy
  # when:
    # status:
    # - success

trigger:
  event:
    - promote
  target:
    - 2.1.0

depends_on:
  - buildtest

---

kind: pipeline
type: docker
name: "2.0.45"

platform:
  os: linux
  arch: amd64

steps:
  - name: Lint Dockerfile
    image: hadolint/hadolint:latest-alpine
    pull: if-not-exists
    commands:
      - hadolint --version
      - hadolint Dockerfile*

  - name: deploy
    image: thegeeklab/drone-docker-buildx
    privileged: true
    settings:
      repo: modem7/dnscrypt-proxy
      # dry_run: true  # disable when not testing
      purge: true
      squash: true
      compress: true
      use_cache: true
      cache_from: "modem7/dnscrypt-proxy:2.0.45"
      platforms:  # if it doesn't work run docker run --privileged --rm tonistiigi/binfmt --install all
        - linux/386
        - linux/amd64
        - linux/arm/v6
        - linux/arm/v7
        - linux/arm64/v8
        - linux/ppc64le
        - linux/s390x
      dockerfile: 2.0.45/Dockerfile
      context: 2.0.45/
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - 2.0.45

  - name: slack
    image: themaz/drone-slack
    settings:
      webhook:
        from_secret: slack_hook
    when:
      status: [ success, failure ]

# Doesn't work currently - https://github.com/christian-korneck/docker-pushrm/blob/master/README.md#limitations
# https://github.com/docker/roadmap/issues/115

# - name: pushrm-dockerhub
  # image: chko/docker-pushrm:1
  # environment:
    # DOCKER_PASS:
      # from_secret: docker_password
    # DOCKER_USER:
      # from_secret: docker_username
    # PUSHRM_FILE: README.md
    # PUSHRM_SHORT: A DNS server container using several UK/European DoH resolution services via DNSCrypt Proxy
    # PUSHRM_TARGET: modem7/dnscrypt-proxy
  # when:
    # status:
    # - success

trigger:
  event:
  - cron
  cron:
  - dnscrypt_2-0-45