---
kind: pipeline
type: docker
name: lint
steps:
  - name: Lint Dockerfile
    image: hadolint/hadolint:latest-debian
    pull: if-not-exists
    commands:
      - hadolint --version
      - hadolint Dockerfile*

---

kind: pipeline
type: docker
name: deploy

platform:
  os: linux
  arch: amd64

steps:
  - name: deploy
    image: thegeeklab/drone-docker-buildx
    privileged: true
    settings:
      repo: modem7/dnscrypt-proxy
      platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8
      purge: true
      dry_run: true  # disable when not testing
      compress: true
      use_cache: true
      cache_from: "modem7/dnscrypt-proxy:latest"
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - latest
        - 2.0.45

- name: slack
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_hook
  when:
    status: [ success, failure ]

depends_on:
  - lint

# - name: pushrm-dockerhub
  # image: chko/docker-pushrm:1
  # environment:
    # DOCKER_PASS:
      # from_secret: docker_password
    # DOCKER_USER:
      # from_secret: docker_username
    # PUSHRM_FILE: README.md
    # PUSHRM_SHORT: A DNS server container using several UK/European DoH resolution services via DNSCrypt Proxy
    # PUSHRM_TARGET: modem7/dnscrypt-proxy
  # when:
    # status:
    # - success

# trigger:
  # event:
  # - promote
  # target:
  # - 2.0.45
  # - production