#!/usr/bin/with-contenv bash

echo "
-----------------------------------
Log Level:   ${LOG_LEVEL:-2}
Time Zone:   $TZ
-----------------------------------
"

exec \
    s6-notifyoncheck -d -n 300 -w 1000 -c "/etc/dnscrypt-healthcheck.sh" \
        dnscrypt-proxy -config /etc/dnscrypt-proxy/dnscrypt-proxy.toml
